import AnimatedText from "@/components/AnimatedText";
import React from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import esraa_pic from "../../public/images/profile/esraa_pic.png";
import Image from "next/image";
import Skills from "@/components/Skills";
import Experience from "@/components/Experience";
import Education from "@/components/Education";
import Training from "@/components/Training"
import TransitionEffect from "@/components/TransitionEffect";

const About = () => {
    return (

        <>
            <Head>
                <title>EsraaAbdelrazek | About page </title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <TransitionEffect />
            <main className="flex w-full flex-col items-center justify-center dark:text-light">
                <Layout className="pt-16">
                    <AnimatedText text='Data Visualized - Stories Realized - Insights Unveiled!' className="mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8" />
                    <h2 className="mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                                About Me
                            </h2>
                    <div className="grid w-full grid-cols-8 gap-16 sm:gap-8">
                    
                        <div className="col-span-5 flex flex-col items-start justify-start md:order-2 md:col-span-8">
                            
                            <p className="font-medium my-2">
                                Hi, I&apos;m Esraa Abdelrazek, and I believe that data is more than just numbers. It&apos;s a powerful tool for making smarter decisions, optimizing processes, and driving real impact. Just as we learn from the past, we can learn from data to improve operations, increase efficiency, and reduce costs.
                            </p>
                            <p className="font-medium my-2">
                                My journey into data analysis and AI started with a deep curiosity about how data shapes our world. While I may still be at the beginning of my career, I have built a solid foundation through hands-on projects and continuous learning. I enjoy solving technical problems, breaking down complex information, and transforming raw data into meaningful insights that guide better decision-making.
                            </p>
                            <p className="font-medium my-2">
                                One of my greatest strengths is <strong>clear and analytical thinking</strong>, which allows me to approach challenges logically and find objective, data-driven solutions. I thrive on structured planning, making me highly effective in tasks that require <strong>organization and strategic execution</strong>. Additionally, I bring a <strong>calm, collaborative, and patient</strong> approach to teamwork, ensuring that challenges are tackled efficiently and with a solutions-focused mindset.
                            </p>
                            <p className="font-medium my-2">
                            My goal is to help businesses, especially startups and small companies, maximize the value of their data By simplifying complex data and turning it into actionable insights, I aim to bridge the gap between information and impact. I&apos;m passionate about continuous learning and eager to expand my expertise in machine learning, predictive analytics, and AI.
                            </p>
                            <p className="font-medium my-2">
                                I look forward to collaborating with businesses that share my vision of using data to create meaningful, strategic growth.
                            </p>
                        </div>


                        <div className="col-span-3 relative h-max  rounded-2xl border-solid border-2  dark:bg-dark dark:border-light
                        border-dark bg-light p-50 margin-top-2  md:order-1 md:col-span-8 lg:flex-col">
                            <div className="absolute  top-1 -right-3 -z-10 w-[102%] h-[103%] 
                            rounded-[2rem] bg-dark dark:bg-light " />
                            <Image src={esraa_pic} alt="Esraa" className="w-full h-auto rounded-2xl"
                                priority
                                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" />

                        </div>

                        {/*<div className="row-span-3">
                        <div className="row-span-1 flex flex-row ">
                            <span className="text-7xl font-semibold">
                                0
                            </span>
                            <h2>satisfied clients</h2>
                        </div>
                        <div className="row-span-1 flex flex-row ">
                            <span className="text-7xl font-semibold">
                                2+
                            </span>
                            <h2>Project completed</h2>
                        </div>
                        <div className=" row-span-1 flex flex-row ">
                            <span className="text-7xl font-semibold">
                                1+
                            </span>
                            <h2>Years of experience</h2>
                        </div>
                    </div>*/}
                    </div>






                    <Skills />
                    <Experience />
                    <Training />
                    <Education />

                </Layout>


            </main>

        </>
    );
};

export default About