import AnimatedText from "@/components/AnimatedText";
import React from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import esraa_pic from "../../public/images/profile/esraa_pic.jpeg";
import Image from "next/image";
import Skills from "@/components/Skills";
import Experience from "@/components/Experience";
import Education from "@/components/Education";
import TransitionEffect from "@/components/TransitionEffect";

const About = () => {
    return (

        <>
            <Head>
                <title>EsraaAbdelrazek | About page </title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <TransitionEffect/> 
            <main className="flex w-full flex-col items-center justify-center dark:text-light">
                <Layout className="pt-16">
                    <AnimatedText text='Data Drives Innovation!' className="mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8" />
                    <div className="grid w-full grid-cols-8 gap-16 sm:gap-8">
                        <div className="col-span-4 flex flex-col items-start  justify-start  md:order-2 md:col-span-8">
                            <h2 className="mb-4 text-lg font-bold uppercase 
                        text-dark/75 dark:text-light/75">About Me</h2>
                            <p className="font-medium">
                                Hi, I'm Esraa, a passionate data scientist and AI
                                enthusiast dedicated to turning data into
                                actionable insights. With a strong foundation in
                                data analysis and  machine learning, I thrive on
                                transforming complex data into innovative
                                solutions that drive impact.
                            </p>
                            <p className="font-medium my-4">
                                My approach to data science goes beyond just
                                crunching numbers—it's about
                                discovering patterns, solving problems,
                                and creating data-driven strategies that empower decision-making.
                            </p>
                            <p className="font-medium">
                                Whether I'm developing predictive models,
                                analyzing big data, or building AI-driven applications,
                                I bring my commitment to excellence and a user-focused mindset to every project I undertake.
                                I look forward to applying my expertise and passion to help you unlock the full potential
                                of your data in your next project.
                            </p>

                        </div>
                        <div className="col-span-4 relative h-max  rounded-2xl border-solid border-2  dark:bg-dark dark:border-light
                        border-dark bg-light p-8  md:order-1 md:col-span-8 lg:flex-col">
                            <div className="absolute  top-0 -right-3 -z-10 w-[102%] h-[103%] 
                            rounded-[2rem] bg-dark dark:bg-light " />
                            <Image src={esraa_pic} alt="Esraa" className="w-full h-auto rounded-2xl "
                                priority
                                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" />
                        </div>

                        {/*<div className="row-span-3">
                        <div className="row-span-1 flex flex-row ">
                            <span className="text-7xl font-semibold">
                                0
                            </span>
                            <h2>satisfied clients</h2>
                        </div>
                        <div className="row-span-1 flex flex-row ">
                            <span className="text-7xl font-semibold">
                                2+
                            </span>
                            <h2>Project completed</h2>
                        </div>
                        <div className=" row-span-1 flex flex-row ">
                            <span className="text-7xl font-semibold">
                                1+
                            </span>
                            <h2>Years of experience</h2>
                        </div>
                    </div>*/}
                    </div>






                    <Skills />

                    <Experience />
                    <Education />

                </Layout>


            </main>

        </>
    );
};

export default About