import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import React from "react";

import Head from "next/head";
import Link from "next/link";
import { GithubIcon } from "@/components/Icons";
import Image from "next/image";
import { motion } from 'framer-motion';
import TransitionEffect from "@/components/TransitionEffect";



import project_1_img from "../../public/images/projects/job_recomandation2.png"
import project_2_img from "../../public/images/projects/top_it_company.png"
import project_3_img from "../../public/images/projects/spotify2.png"
import project_4_img from "../../public/images/projects/football.png"
const FramerImage = motion(Image);
const FeaturedProject = ({type, title,summary, img, link, github}) => {
    return(
        <article className="w-full flex items-center justify-between relative rounded-br-2xl
        rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12 dark:bg-dark
         dark:border-light  lg:flex-col  lg:p-8 xs:rounded-2xl xs:rounded-br-3xl xs:p-4">
            <div className="absolute  top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem]
            bg-dark dark:bg-light rounded-br-3xl  xs:-right-2 xs:w-full sm:h-[102%] xs:rounded-[1.5rem]" />

            <Link href={link} target="_blank" 
                className="w-1/2 cursor-pointer overflow-hidden rounded-lg lg:w-full">
                <FramerImage src={img} alt={title} className="w-full h-auto"
                whileHover={{scale: 1.05}} transition={{duration: 0.2}}
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw" />
            </Link>
            <div className="w-1/2 flex flex-col items-start justify-between pl-6 lg:w-full lg:pl-0 lg:pt-6">
                <span className="text-primary font-medium text-xl dark:text-primaryDark xs:text-base">{type}</span>
                <Link href={link} target="_blank"
                className="hover:underline underline-offset-2">
                    <h2 className="my-2 w-full text-left font-bold text-4xl dark:text-light sm:text-sm">{title}</h2>
                </Link>
                <p className="my-2 font-medium text-dark dark:text-light sm:text-sm">{summary}</p>
                <div className="mt-2 flex items-center">
                    <Link href={github} target="_blank" className="w-10 "> <GithubIcon/> </Link>
                    <Link href={link} target="_blank"
                    className="ml-4 rounded-lg bg-dark py-2 px-6 text-lg font-semibold text-light
                     dark:bg-light dark:text-dark sm:px-4 sm:text-base"
                    >Visit Project</Link>
                </div>

            </div>
        </article>

    )


};

const Project = ({type, title, img, link, github}) => {
    return(
        <article className="w-full flex flex-col items-center justify-center  rounded-br-2xl
        rounded-2xl border border-solid border-dark bg-light  p-6 relative dark:bg-dark dark:border-light xs:p-4">
            <div className="absolute  top-0 -right-3 -z-10 w-[100%] h-[102%] rounded-[2rem]
             rounded-br-2xl bg-dark dark:bg-light
             md:-right-2 md:w-full xs:h-[102%] xs:rounded-[1.5rem]" />

            <Link href={link} target="_blank" className="w-full cursor-pointer overflow-hidden rounded-lg">
                <FramerImage src={img} alt={title} className="w-full h-auto" 
                whileHover={{scale: 1.05}} transition={{duration: 0.2}}
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw" 
                />
            </Link>
            <div className="w-full flex flex-col items-start justify-between mt-4">
                <span className="text-primary font-medium text-xl dark:text-primaryDark lg:text-lg md:text-base">{type}</span>
                <Link href={link} target="_blank"
                className="hover:underline underline-offset-2">
                    <h2 className="my-2 w-full text-left font-bold text-3xl lg:text-2xl ">{title}</h2>
                </Link>
                <div className="w-full mt-2 flex items-center justify-between">
                <Link href={link} target="_blank"
                    className="text-lg font-semibold underline text-dark/75 dark:text-light/75 md:text-base"
                    >Visit</Link>
                    <Link href={github} target="_blank" className="w-8 md:w-6"> <GithubIcon/> </Link>
                    
                </div>

            </div>
        </article>

    )
}
const projects = () => {
    return (
        <>
            <Head>
                <title>EsraaAbdelrazek | Projects page </title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <TransitionEffect/> 
            <main className="flex w-full mb-16 flex-col items-center justify-center dark:text-light">
                <Layout className="pt-16">
                    <AnimatedText text={'Imagination Trumps Knowledge!'} 
                    className="mb-16 lg:!text-7xl sm:!text-6xl sm:!mb-8 xs:!text-4xl" />

                    <div className="grid grid-cols-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0">
                        <div className="col-span-12">
                           <FeaturedProject
                           type="NLP"
                           title="Job Recommendation and Filtering System"
                           summary="Collaboratively developed a job recommendation and filtering system using machine learning, designed models, implemented data filtering. Demonstrated leadership, teamwork, decision-making, problem-solving, and time management skills by facilitating communication, delegating tasks, and ensuring project milestones were met on time." 
                           img={project_1_img}
                           link="https://www.canva.com/design/DAFnrTtnyBc/wDG92qtlamPBourWG-04BQ/edit?utm_content=DAFnrTtnyBc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"
                           github="https://github.com/EsraaMosaad/GP_Job-Recommendation-and-Filtering_doc/tree/main"/>
                        
                        </div>
                        <div className="col-span-6 sm:col-span-12">
                            <Project type="Web scrapping"
                            title="Top IT Companies Worldwide"
                            img={project_2_img}
                            link="https://github.com/EsraaMosaad/Top-IT-Companies-Worldwide"
                            github="https://github.com/EsraaMosaad/Top-IT-Companies-Worldwide"/>
                            

                        </div>
                        <div className="col-span-6 sm:col-span-12">
                        <Project type="Computer Vision "
                            title="Semantic Segmentation for Soccer Analytics Using U-Net"
                            img={project_4_img}
                            link="/"
                            github="https://github.com/EsraaMosaad/ASDC-AI-Data-analysis-internship/blob/main/Task%203/Report.md"/>
                            
                        </div>
                        <div className="col-span-12">
                        <FeaturedProject
                           type="streamlit dashboard"
                           title="Spotify-Million-Playlist-Dataset-Analysis-and-Visualization"
                           summary="This project aims to analyze a dataset from Spotify containing playlists and their associated tracks. The dataset consists of 250,000 playlists and 16,596,692 tracks, which were processed using PySpark for data cleaning and analysis, followed by visualization in a Streamlit dashboard." 
                           img={project_3_img}
                           link="https://github.com/EsraaMosaad/Spotify-Million-Playlist-Dataset-Analysis-and-Visualization/blob/main/app.py"
                           github="https://github.com/EsraaMosaad/Spotify-Million-Playlist-Dataset-Analysis-and-Visualization"/>
                        
                        </div>
                        {/*<div className="col-span-6 sm:col-span-12">
                        <Project type="Graduation project"
                            title="Job Recommendation and Filtering System"
                            img={project_2_img}
                            link="https://www.canva.com/design/DAFnrTtnyBc/wDG92qtlamPBourWG-04BQ/edit?utm_content=DAFnrTtnyBc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"
                            github="https://github.com/EsraaMosaad/GP_Job-Recommendation-and-Filtering_doc/tree/main"/>
                            
                        </div>
                        <div className="col-span-6 sm:col-span-12">
                            <Project type="Graduation project"
                            title="Job Recommendation and Filtering System"
                            img={project_2_img}
                            link="https://www.canva.com/design/DAFnrTtnyBc/wDG92qtlamPBourWG-04BQ/edit?utm_content=DAFnrTtnyBc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"
                            github="https://github.com/EsraaMosaad/GP_Job-Recommendation-and-Filtering_doc/tree/main"/>
                            
                        </div> */}

                    </div>
                </Layout>
            </main>
        </>
    );
};

export default projects;